[project]
site_name = "Business Automation"
site_description = "Business Automation"
site_author = "Thomas Yang"
repo_url = "https://github.com/IBM/business-automation"
site_url = "https://ibm.github.io/business-automation"
copyright = "Copyright &copy; 2026 IBM Corporation - <a href=\"#__consent\">Change cookie settings</a>"
docs_dir = "docs"
use_directory_urls = false
exclude_docs = """
README*.md
"""

nav = [
    {Introduction = "index.md"},
    {Overview = "overview.md"}
]

[project.theme]
language = "en"
custom_dir = "docs/overrides"
logo = "assets/logo.png"
favicon = "assets/favicon.ico"
features = [
    "navigation.path",
    "announce.dismiss",
    "navigation.top",
    "navigation.footer",
    "navigation.indexes",
    "navigation.sections",
    "navigation.tracking",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.instant.progress",
#    "navigation.tabs",
#    "navigation.expand",
#    "toc.integrate",
    "search.share",
    "search.suggest",
    "search.highlight",
]

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
accent = "green"
primary = "deep purple"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
accent = "light green"
primary = "deep purple"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"


# ----------------------------------------------------------------------------
# In the "palette" subsection you can configure options for the color scheme.
# You can configure different color # schemes, e.g., to turn on dark mode,
# that the user can switch between. Each color scheme can be further
# customized.
#
# Read more:
# - https://zensical.org/docs/setup/colors/
# ----------------------------------------------------------------------------
[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"


# ----------------------------------------------------------------------------
# The "extra" section contains miscellaneous settings.
# ----------------------------------------------------------------------------
[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://ibm.com"


